version: "3.9"

services:
  nextjs:
    container_name: comic-picture-book
    build: .
    env_file:
      - config/env.production.example
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - ./public/comic-assets:/app/public/comic-assets
    restart: unless-stopped

